<a href="https://colab.research.google.com/github/divx1979/PyTorch/blob/Projects/TORCH_INTRO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch 101

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
!pip install torch torchvision

In [ ]:
import torch

# define vars
a = torch.tensor(1.5)
b = torch.tensor(2.5)
c = torch.add(a, b)
print(c)

tensor(4.)


In [ ]:
# rep version
print(torch.__version__)

2.9.0+cu126


In [ ]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# Fundamentals:



**Create Tensors From Lists, NumPy & Panda**



In [ ]:
## A) From Python List
## Think of it like:
## You hand PyTorch a list → PyTorch hands you a tensor

In [ ]:
import torch

data_list = [1, 2, 3, 4]
t = torch.tensor(data_list)
print(t)

tensor([1, 2, 3, 4])


In [ ]:
## B) From NumPy Array
## Translation:
## NumPy → PyTorch (they are cousin)

In [ ]:
import numpy as np
import torch

np_arr = np.array([10, 20, 30])
t = torch.from_numpy(np_arr)
print(t)

tensor([10, 20, 30])


In [ ]:
## C) From pandas DataFrame / Series
## Why .values?
## Because pandas holds data behind the scenes → .values exposes it → PyTorch tensorizes it

In [ ]:
import pandas as pd
import torch

df = pd.DataFrame({"age": [21, 25, 32]})
t = torch.tensor(df["age"].values)
print(t)

tensor([21, 25, 32])


# 2) Reshaping: unsqueeze, reshape, transpose

In [ ]:
## 1) .unsqueeze() → Add a dimension
## Layman analogy:
## “Add an extra box around the items."

In [ ]:
x = torch.tensor([10, 20, 30])   # shape: [3]

x2 = x.unsqueeze(1)
print(x2, x2.shape)

tensor([[10],
        [20],
        [30]]) torch.Size([3, 1])


In [ ]:
## 2) .reshape() → Change the shape you want
## Think: “Rearrange the same stuff into new rows/colum"

In [ ]:
x = torch.arange(6)  # [0 1 2 3 4 5]

x2 = x.reshape(2, 3)
print(x2)

tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
## 3) .transpose() → Swap dimension
## This flips rows ↔ column

In [ ]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

xT = x.transpose(0, 1)
print(xT)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


# Excercise

In [ ]:
sales_data = torch.tensor([[100, 120, 130, 110],   # Product A
                           [ 90,  95, 105, 125],   # Product B
                           [140, 115, 120, 150]    # Product C
                          ], dtype=torch.float32)

In [ ]:
## Total Sales For Product B Are:

tot_sales_product_B = torch.sum(sales_data[1, :])
print(tot_sales_product_B)

tensor(415.)


In [ ]:
## Find Months Where Sales For Prod C were > 130

mask = sales_data[:3, :] > 130

high_sales_mask_months = sales_data[2] > 130
print(high_sales_mask_months)


tensor([ True, False, False,  True])


In [ ]:
# 3. Get sales for Feb and Mar for all products.
sales_feb_mar = sales_data[:, 1:3]
print(sales_feb_mar)

tensor([[120., 130.],
        [ 95., 105.],
        [115., 120.]])


In [ ]:
# Exercise 2: Image Batch Transformation
# You're working on a computer vision model and have a batch of 4 grayscale images, each of size 3x3 pixels. The data is currently in a tensor with the shape [4, 3, 3], which represents [batch_size, height, width].

# For processing with certain deep learning frameworks, you need to transform this data into the [batch_size, channels, height, width] format. Since the images are grayscale, you'll need to:

# Add a new dimension of size 1 at index 1 to represent the color channel.
# After adding the channel, you realize the model expects the shape [batch_size, height, width, channels]. Transpose the tensor to swap the channel dimension with the last dimension

# A batch of 4 grayscale images, each 3x3
image_batch = torch.rand(4, 3, 3)

print("ORIGINAL BATCH SHAPE:", image_batch.shape)
print("-" * 45)

### START CODE HERE ###

# 1. Add a channel dimension at index 1.
image_batch_with_channel = image_batch.unsqueeze(1)

# 2. Transpose the tensor to move the channel dimension to the end.
# Swap dimension 1 (channels) with dimension 3 (the last one).
image_batch_transposed = image_batch_with_channel.transpose(1, 3)

### END CODE HERE ###


print("\nSHAPE AFTER UNSQUEEZE:", image_batch_with_channel.shape)
# print("SHAPE AFTER TRANSPOSE:", image_batch_transposed.shape)

ORIGINAL BATCH SHAPE: torch.Size([4, 3, 3])
---------------------------------------------

SHAPE AFTER UNSQUEEZE: torch.Size([4, 1, 3, 3])


# New

In [ ]:
x = torch.tensor([2.0, 4.0, 6.0])
y = torch.tensor([1.0, 2.0, 3.0])
result = x / y + 5
print(result)

tensor([7., 7., 7.])


In [ ]:
x = torch.tensor([25.0])
x = x.unsqueeze(0)
x = x.squeeze()
print(x.shape)

torch.Size([])


## Pushing your Colab Notebook to Git

This section will guide you through the process of pushing your current Colab notebook to a Git repository.

### Step 1: Configure Git User Information

First, you need to tell Git who you are. Replace `Your Name` and `your.email@example.com` with your actual Git credentials.

In [4]:
!git config --global user.name "divx1979"
!git config --global user.email "dbhatt245@gmail.com"

### Step 2: Clone your Git Repository

Now, clone your repository. Replace `your_repository_url` with the actual URL of your Git repository (e.g., from GitHub, GitLab, Bitbucket). Make sure to use the HTTPS URL for public repositories, or SSH if you have configured SSH keys in Colab.

After cloning, you'll see a new directory with the name of your repository in the Colab file browser.

In [5]:
!git clone "https://github.com/divx1979/PyTorch"

Cloning into 'PyTorch'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.


### Step 3: Save and Move Your Notebook

1.  **Save your current notebook**: Go to `File > Save` in the Colab menu to ensure all your latest changes are saved.
2.  **Download your notebook**: Go to `File > Download > Download .ipynb`.
3.  **Upload the notebook to the cloned repository folder**: In the Colab file browser (left sidebar), navigate into the newly cloned repository folder. Then, click the 'Upload to session storage' icon (folder with an upward arrow) and upload the `.ipynb` file you just downloaded.

Alternatively, you can move the notebook directly if you know its current path and the cloned repo's path (e.g., if you haven't renamed it).

Replace `Your_Notebook_Name.ipynb` with the actual name of your notebook and `your_repo_name` with the name of your cloned repository folder.

```python
!mv "/content/Your_Notebook_Name.ipynb" "/content/your_repo_name/"
```

### Step 4: Add, Commit, and Push Your Changes

Navigate into your repository folder, add the notebook, commit the changes, and push them to your remote repository.

Replace `your_repo_name` with the name of your cloned repository folder and `Your_Notebook_Name.ipynb` with the name of your notebook.

When you run the `git push` command, you might be prompted to enter your Git username and password. If you have 2FA enabled, you might need to use a Personal Access Token (PAT) instead of your password.

In [6]:
%cd PyTorch
!git add TORCH_INTRO.ipynb
!git commit -m "Add my Colab notebook"
!git push origin main # or 'master', depending on your branch name

/content/PyTorch
fatal: pathspec 'TORCH_INTRO.ipynb' did not match any files
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address
